---

# Use a preconfigured gitbub stripes platform
with_github: true
stripes_github_project: https://github.com/folio-org/stripes-demo-platform

# OR specify stripes configuration here and configure from ansible templates 
stripes_core_version: "^0.7.0"
stripes_modules:
  - { name: "@folio/users", version: "^1.1.0" }
  - { name: "@folio/items", version: "^1.1.0" }
  - { name: "@folio/scan", version: "^0.2.0" }
  - { name: "@folio/trivial", version: "^0.0.2-test" }

# disable okapi-console - https://issues.folio.org/browse/STRIPES-264
#  - { name: "@folio/okapi-console", version: "^0.0.1-test" }


# Other relevant vars
stripes_conf_dir: /etc/folio/stripes
stripes_okapi_port: 9130
disable_auth: false
stripes_okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ stripes_okapi_port }}"
stripes_tenant: diku
# host address to map container to. '127.0.0.1' by default  
stripes_host_address: '127.0.0.1'
#
# optional nginx proxy. disabled by default.
#
with_nginx: false
nginx_port: 80
# can override with ec2_facts 'ansible_ec2_public_hostname' for AWS
nginx_servername: localhost

# NPM repository settings
folio_npm_base_url: repository.folio.org/repository/
folio_npm_repo: npm-folio

#
# Disabled by default
# 
npm_proxy: false
npm_authtoken: ''
