---

stripes_modules:
  - { name: "@folio/okapi-console", version: "^0.0.1-test" }
  - { name: "@folio/users", version: "^0.0.1-test" }
  - { name: "@folio/items", version: "^0.0.1-test" }
  - { name: "@folio/scan", version: "^0.0.1" }

stripes_core_version: "^0.2.0"
stripes_conf_dir: /etc/folio/stripes
stripes_okapi_port: 9130
disable_auth: false
stripes_okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ stripes_okapi_port }}"
stripes_tenant: diku
# host address to map container to. '127.0.0.1' by default  
stripes_host_address: '127.0.0.1'
#
# optional nginx proxy. disabled by default.
#
with_nginx: false
nginx_port: 80
# can override with ec2_facts 'ansible_ec2_public_hostname' for AWS
nginx_servername: localhost

#
# for use by FOLIO CI. disabled by default
# 
folioci: false
npm_authtoken: ''
