---
# sometimes this role is run right after okapi is started.  Wait some
# interval to ensure okapi is fully started
- wait_for: timeout=15

# Authenticate to supertenant if required
- name: login to supertenant if authn interface exists
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    body_format: json
    body: "{'username': '{{ superuser_username }}', 'password': '{{ superuser_password }}' }"
    status_code: 201, 404
  register: login_result
  when: supertenant_token is not defined
- name: Set Okapi token if supertenant is secured
  set_fact:
    supertenant_token: "{{ login_result['x_okapi_token'] }}"
  when: login_result.status is defined and login_result.status == 201

# Role to load a dummy tenant
- name: Check tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ tenant }}"
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    status_code: 200, 404
  register: tenant_check

- name: Create tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants"
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
    body_format: json
    body: "{{ tenant_json }}"
    status_code: 201
  when: tenant_check.status == 404
  register: tenant_created
  changed_when: "tenant_created.status == 201"

# Returns 400 if already enabled
- name: Enable Okapi internal module for tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ tenant }}/modules"
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
    body_format: json
    body: '{ "id": "okapi" }'
    status_code: 201,400
  register: tenant_enable_okapi
  changed_when: "tenant_enable_okapi.status == 201"
  when: enable_okapi
