---
# Role to enable mod-metadata modules for the sample tenant and load
# sample data
# wait a few seconds to make sure modules are spun up
- wait_for: timeout=10

- name: Check tenant registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules/{{ item.module }}"
    status_code: 200, 404
  register: tenant_mod_metadata
  with_items: "{{ mod_metadata_modules }}"

- name: Enable mod-metadata modules for tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules"
    method: POST
    body_format: json
    body: '{ "id" : "{{ item.module }}" }'
    status_code: 201
  register: mod_metadata_enable
  changed_when: mod_metadata_enable.status == 201
  when: tenant_mod_metadata.results[item.index].status == 404
  with_items: "{{ mod_metadata_modules }}"

- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: mod_metadata_login
  when: auth_required

- name: Grant additional permissions to {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/perms/users/{{ admin_user.username }}/permissions"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      X-Okapi-Token: "{{ mod_metadata_login.x_okapi_token }}"
      Accept: application/json
    body: '{ "permissionName" : "{{ item }}" }'
    status_code: 200,422
  register: admin_perms
  changed_when: admin_perms.status == 200
  with_items: "{{ admin_permissions }}"
  when: auth_required

- name: Check for sample instances
  uri:
    url: "{{ okapi_url }}/instance-storage/instances"
    headers:
      Content-Type: application/json
      X-Okapi-Tenant: diku
      Accept: application/json
      X-Okapi-Token: "{{ mod_metadata_login.x_okapi_token | default('token') }}"
  register: inventory_instances

- name: Check for sample items
  uri:
    url: "{{ okapi_url }}/item-storage/items"
    headers:
      Content-Type: application/json
      X-Okapi-Tenant: diku
      Accept: application/json
      X-Okapi-Token: "{{ mod_metadata_login.x_okapi_token | default('token') }}"
  register: inventory_items

# fails with 422 error if already loaded
- name: Load inventory storage material types
  uri:
    url: "{{ okapi_url }}/material-types"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
      X-Okapi-Token: "{{ mod_metadata_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('file', item) }}"
    status_code: 201, 422
  register: load_mtype
  changed_when: load_mtype.status == 201
  with_fileglob:
    - mtypes/*.json

# fails with 400 if already loaded
- name: Load inventory storage loan types
  uri:
    url: "{{ okapi_url }}/loan-types"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
      X-Okapi-Token: "{{ mod_metadata_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('file', item) }}"
    status_code: 201, 400
  register: load_ltype
  changed_when: load_ltype.status == 201
  with_fileglob:
    - loantypes/*.json

- name: Load inventory storage instances
  uri:
    url: "{{ okapi_url }}/instance-storage/instances"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
      X-Okapi-Token: "{{ mod_metadata_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('file', item) }}"
    status_code: 201
  register: load_instance
  changed_when: load_instance.status == 201
  when: inventory_instances.json.totalRecords == 0
  with_fileglob:
    - instances/*.json
  
- name: Load inventory storage items
  uri:
    url: "{{ okapi_url }}/item-storage/items"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
      X-Okapi-Token: "{{ mod_metadata_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('file', item) }}"
    status_code: 201
  register: load_item
  changed_when: load_item.status == 201
  when: inventory_items.json.totalRecords == 0
  with_fileglob:
    - items/*.json

- name: Copy sample MODS data
  become: yes
  copy: src=multiple-mods-records.xml dest=/etc/.mod-metadata-mods_ansible.xml
  register: mods_sample

- name: Copy larger sample
  become: yes
  copy: src=many_mods.xml dest=/etc/.mod-metadata-mods-large_ansible.xml
  register: mods_larger

- name: Load sample data from MODS ingest
  command: "/usr/bin/curl -X POST -H 'Content-type: multipart/form-data' -H 'X-Okapi-Tenant: diku' -H 'X-Okapi-Token: {{ mod_metadata_login.x_okapi_token | default('token') }}' -F upload=@/etc/.mod-metadata-mods_ansible.xml {{ okapi_url }}/inventory/ingest/mods"
  when: mods_sample.changed

- name: Load larger sample data from MODS ingest
  command: "/usr/bin/curl -X POST -H 'Content-type: multipart/form-data' -H 'X-Okapi-Tenant: diku' -H 'X-Okapi-Token: {{ mod_metadata_login.x_okapi_token | default('token') }}' -F upload=@/etc/.mod-metadata-mods-large_ansible.xml {{ okapi_url }}/inventory/ingest/mods"
  when: mods_larger.changed
