---
okapi_port: 9130

okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"

pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432

module_database: okapi_modules

# Prefixes for module ids
mod_auth_prefixes:
  - permissions-module
  - authtoken-module
  - login-module
  - mod-users

# Schema names for db
mod_permissions_schema: diku_permissions_module
mod_login_schema: diku_login_module
mod_users_schema: diku_mod_users

admin_user:
  username: diku_admin
  password: admin
  hash: 52DCA1934B2B32BEA274900A496DF162EC172C1E
  salt: 483A7C864569B90C24A0A6151139FF0B95005B16
  permissions: "\\\"perms.all\\\""
  id: 1ad737b0-d847-11e6-bf26-cec0c932ce01
  first_name: DIKU
  last_name: ADMINISTRATOR
  email: admin@diku.example.org

admin_permissions:
  - perms.all
  - login.all
  - users.all
  - module.trivial.enabled
  - module.users.enabled
  - module.items.enabled
  - module.instances.enabled
  - module.checkin.enabled
  - module.checkout.enabled
  - module.scan.enabled
  - module.requests.enabled
  - module.organization.enabled
  - settings.enabled
  - settings.checkout.enabled
  - settings.developer.enabled
  - settings.loan-rules.all
  - settings.loan-policies.all
  - settings.loan-types.all
  - settings.material-types.all
  - settings.usergroups.all
  - settings.addresstypes.all
  - ui-users.editpermsets 
  - ui-organization.settings.key-bindings
  - ui-organization.settings.locale
  - ui-organization.settings.plugins
  - ui-organization.settings.sso

# Permissions not defined in module descriptors
additional_permissions: []

mod_auth_users:
  - username: auth_test1
    password: diku
    permissions:
      - module.trivial.enabled
      - module.users.enabled
      - module.items.enabled
      - module.scan.enabled
      - module.requests.enabled
      - module.okapi-console.enabled
      - module.organization.enabled
      - module.settings.enabled
  - username: auth_test2
    password: diku

