---
okapi_port: 9130

okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"

pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432

module_database: okapi_modules

mod_users_id: users-module

mod_auth_modules:
  - { index: 0, module: permissions-module }
  - { index: 1, module: authtoken-module }
  - { index: 2, module: login-module }
  - { index: 3, module: "{{ mod_users_id }}" }

admin_user:
  username: diku_admin
  password: admin
  hash: 52DCA1934B2B32BEA274900A496DF162EC172C1E
  salt: 483A7C864569B90C24A0A6151139FF0B95005B16
  permissions: "\\\"perms.all\\\""
  id: 1ad737b0-d847-11e6-bf26-cec0c932ce01
  first_name: DIKU
  last_name: ADMINISTRATOR
  email: admin@diku.example.org

admin_permissions:
  - perms.all
  - login.all
  - users.all
  - module.trivial.enabled
  - module.users.enabled
  - module.items.enabled
  - module.scan.enabled
  - module.requests.enabled
  - module.organization.enabled
  - module.settings.enabled

# Permissions not defined in backend module descriptors
additional_permissions:
  - { permissionName: module.trivial.enabled, displayName: "UI: Trivial module is enabled", subPermissions: "[]", mutable: "false" }

mod_auth_users:
  - username: auth_test1
    password: diku
    permissions:
      - module.trivial.enabled
      - module.users.enabled
      - module.items.enabled
      - module.scan.enabled
      - module.requests.enabled
      - module.okapi-console.enabled
      - module.organization.enabled
      - module.settings.enabled
  - username: auth_test2
    password: diku

