---
# Ansible playbook to deploy Okapi and FOLIO modules
# Build a Vagrant box to package as a demo system
- hosts: build_demo
  roles:
    - common
    - postgresql
    - okapi
    - mod-users
    - mod-metadata
    - mod-loan-storage
    - mod-circulation
    - mod-circulation-data
    - mod-auth
    - mod-auth-data
    - mod-auth-demo-users
    - mod-users-bl
    - mod-users-bl-data
    - stripes-docker
  tasks:
    - name: Copy vagrant-tidy.sh to /root
      become: yes
      copy: src=vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

    - debug:
        msg: To create a Vagrant box from this VM, you want to run the vagrant-tidy.sh script, then use vagrant package

# Build a Vagrant box to package as a backend system
- hosts: build_backend
  roles:
    - common
    - postgresql
    - okapi
    - mod-users
    - mod-metadata
    - mod-loan-storage
    - mod-circulation
    - mod-circulation-data
  tasks:
    - name: Copy vagrant-tidy.sh to /root
      become: yes
      copy: src=vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

    - debug:
        msg: To create a Vagrant box from this VM, you want to run the vagrant-tidy.sh script, then use vagrant package

# Build a Vagrant box as a backend system with mod-auth
- hosts: build_backend_auth
  roles:
    - common
    - postgresql
    - okapi
    - mod-users
    - mod-metadata
    - mod-loan-storage
    - mod-circulation
    - mod-circulation-data
    - mod-auth
    - mod-auth-data
    - mod-auth-demo-users
    - mod-users-bl
    - mod-users-bl-data

  tasks:
    - name: Copy vagrant-tidy.sh to /root
      become: yes
      copy: src=vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

    - debug:
        msg: To create a Vagrant box from this VM, you want to run the vagrant-tidy.sh script, then use vagrant package

# Build a Vagrant box to support FOLIO Developer Curriculum
- hosts: build_curriculum
  roles:
    - common
    - openjdk-8
    - maven-3
    - nodejs
    - yarn
    - ansible
    - docker-engine

  tasks:
    - name: Move to Node.js 6.X lts
      become: yes
      shell: n lts && touch /etc/.set_nodedefault_ansible
      args:
        creates: /etc/.set_nodedefault_ansible

    - name: Setup Ansible inventory for localhost
      become: yes
      lineinfile:
        dest: /etc/ansible/hosts
        line: localhost ansible_connection=local

    - name: Clone curriculum repository
      git: repo=https://github.com/folio-org/curriculum dest={{ ansible_env.HOME }}/curriculum

    - name: Copy vagrant-tidy.sh to /root
      become: yes
      copy: src=vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

    - debug:
        msg: To create a Vagrant box from this VM, you want to run the vagrant-tidy.sh script, then use vagrant package

