---
# Ansible playbook to deploy Okapi and FOLIO modules
# Group for development
# Vagrantfile puts default VM into this group
- hosts: dev
  roles:
    - okapi-docker
    - mod-users-docker
    - mod-users-data
