---
# Ansible playbook to deploy Okapi and FOLIO modules
# Provision a host as a backend FOLIO system
- hosts: folio-backend
  roles:
    - common
    - postgresql
    - okapi
    - okapi-deploy-modules

- hosts: snapshot
  roles:
    - common
    - postgresql
    - okapi
    - stripes-docker
    - okapi-deploy-config
    - tenant-admin-permissions

# Provision a host with the sample tenant and data
- hosts: folio-sample-data-stable
  roles:
    - mod-auth-data
    - mod-configuration-data
    - mod-users-data 
    - mod-users-bl-data
    - mod-circulation-data
    - mod-notes-data
    - mod-auth-demo-users

# Provision a host with the sample tenant and data
- hosts: folio-sample-data-testing
  roles:
    - mod-auth-data
    - mod-configuration-data
    - mod-users-data 
    - mod-users-bl-data
    - mod-login-saml-data
    - mod-user-import-data
    - mod-circulation-data
    - mod-notes-data
    - mod-graphql-data
    - mod-kb-ebsco-data
    - mod-codex-mock-data
    - mod-codex-mux-data
    - mod-codex-inventory-data
    - mod-codex-ekb-data
    - mod-auth-demo-users

# Provision a host with the sample tenant and data
- hosts: folio-sample-data-snapshot
  roles:
    - mod-auth-data
    - mod-configuration-data
    - mod-users-data 
    - mod-users-bl-data
    - mod-login-saml-data
    - mod-circulation-data
    - mod-notes-data
    - mod-kb-ebsco-data
    - mod-codex-ekb-data
    - mod-auth-demo-users

# Provision a host with a Stripes build
# Post module descriptors to Okapi
- hosts: stripes-build
  roles:
    - stripes-build
    - tenant-admin-permissions

# Provision a host as a Stripes server
- hosts: stripes
  roles:
    - stripes-docker
    - tenant-admin-permissions

# Roles for packaging
- hosts: vagrant
  roles:
    - maven-3

- hosts: packer
  roles:
    - vagrant-tidy

# Provision a host to support FOLIO Developer Curriculum
- hosts: build_curriculum
  roles:
    - common
    - openjdk-8
    - maven-3
    - nodejs
    - yarn
    - ansible
    - docker-engine

  tasks:
    - name: Move to Node.js 6.X lts
      become: yes
      shell: n lts && touch /etc/.set_nodedefault_ansible
      args:
        creates: /etc/.set_nodedefault_ansible

    - name: Setup Ansible inventory for localhost
      become: yes
      lineinfile:
        dest: /etc/ansible/hosts
        line: localhost ansible_connection=local

    - name: Clone curriculum repository
      git: repo=https://github.com/folio-org/curriculum dest={{ ansible_env.HOME }}/curriculum

