---
# Ansible playbook to deploy Okapi and FOLIO modules
# Provision a host as a backend FOLIO system
- hosts: folio-backend
  roles:
    - common
    - postgresql
    - okapi
    - okapi-register-modules
    - okapi-deploy-modules
    - mod-auth-data
    - mod-configuration-data
    - mod-users-data 
    - mod-users-bl-data 
    - mod-circulation-data 
    - mod-auth-demo-users

# Provision a host as a Stripes server
- hosts: stripes
  roles:
    - stripes-docker 

# Provision a host to support FOLIO Developer Curriculum
- hosts: build_curriculum
  roles:
    - common
    - openjdk-8
    - maven-3
    - nodejs
    - yarn
    - ansible
    - docker-engine

  tasks:
    - name: Move to Node.js 6.X lts
      become: yes
      shell: n lts && touch /etc/.set_nodedefault_ansible
      args:
        creates: /etc/.set_nodedefault_ansible

    - name: Setup Ansible inventory for localhost
      become: yes
      lineinfile:
        dest: /etc/ansible/hosts
        line: localhost ansible_connection=local

    - name: Clone curriculum repository
      git: repo=https://github.com/folio-org/curriculum dest={{ ansible_env.HOME }}/curriculum

