---
# Ansible playbook to deploy Okapi and FOLIO modules
# Build a Vagrant box to package as a demo system
- hosts: build_demo
  roles:
    - okapi
    - mod-users
    - mod-users-data
    - mod-metadata
    - mod-metadata-data
    - stripes
  tasks:
    - name: Copy vagrant-tidy.sh to /root
      become: yes
      copy: src=roles/okapi-demo/files/vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

    - debug:
        msg: To create a Vagrant box from this VM, you want to run the vagrant-tidy.sh script, then use vagrant package

# Build a Vagrant box to package as a backend system
- hosts: build_backend
  roles:
    - okapi
    - mod-users
    - mod-users-data
    - mod-metadata
    - mod-metadata-data
  tasks:
    - name: Copy vagrant-tidy.sh to /root
      become: yes
      copy: src=roles/okapi-demo/files/vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

    - debug:
        msg: To create a Vagrant box from this VM, you want to run the vagrant-tidy.sh script, then use vagrant package

# Build a Vagrant box as a backend system with mod-auth
- hosts: build_backend_auth
  roles:
    # - okapi
    # - mod-users
    # - mod-users-data
    # - mod-metadata
    # - mod-metadata-data
    - mod-auth-data

  tasks:
    - name: Copy vagrant-tidy.sh to /root
      become: yes
      copy: src=roles/okapi-demo/files/vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

    - debug:
        msg: To create a Vagrant box from this VM, you want to run the vagrant-tidy.sh script, then use vagrant package

