---
# Ansible playbook to deploy Okapi and FOLIO modules
# Provision a host as a backend FOLIO system
- hosts: stable:stable-backend:testing:snapshot:minimal
  roles:
    - common
    - postgresql
    - okapi

# Configure builds
- name: Configure stable build
  hosts: stable:stable-backend
  roles:
    - okapi-deploy-modules
    - enable-tenant-modules

- name: Configure testing build
  hosts: testing
  roles:
    - okapi-deploy-modules
    - enable-tenant-modules
    - create-tenant-admin
    - tenant-admin-permissions

- name: Configure snapshot build
  hosts: snapshot
  roles:
    - okapi-deploy-config
    - create-tenant-admin
    - tenant-admin-permissions

# Sample data for stable
- name: Load sample data for stable build
  hosts: stable:stable-backend
  roles:
    - deprecated/mod-auth-data
    - deprecated/mod-inventory-data
    - mod-circulation-data
    - mod-auth-demo-users

# Sample data for testing and snapshot
- name: Load sample data for testing/snapshot builds
  hosts: testing:snapshot
  roles:
    - role: module-sample-data
      module_name: mod-inventory-storage
      repository: "https://github.com/folio-org/mod-inventory-storage"
      module_version: FOLIO-1313-align-data
      duplicate_key_error: 400
      files:
        - { load_endpoint: /classification-types, fileglob: reference-data/classification-types/*.json }
        - { load_endpoint: /contributor-name-types, fileglob: reference-data/contributor-name-types/*.json }
        - { load_endpoint: /contributor-types, fileglob: reference-data/contributor-types/*.json }
        - { load_endpoint: /identifier-types, fileglob: reference-data/identifier-types/*.json }
        - { load_endpoint: /instance-formats, fileglob: reference-data/instance-formats/*.json }
        - { load_endpoint: /instance-types, fileglob: reference-data/instance-types/*.json }
        - { load_endpoint: /loan-types, fileglob: reference-data/loan-types/*.json }
        - { load_endpoint: /location-units/institutions, fileglob: reference-data/location-units/institutions/*.json, dup_override: 422 }
        - { load_endpoint: /location-units/campuses, fileglob: reference-data/location-units/campuses/*.json, dup_override: 422 }
        - { load_endpoint: /location-units/libraries, fileglob: reference-data/location-units/libraries/*.json,  dup_override: 422 }
        - { load_endpoint: /locations, fileglob: reference-data/locations/*.json, dup_override: 422 }
        - { load_endpoint: /material-types, fileglob: reference-data/material-types/*.json, dup_override: 422 }
        - { load_endpoint: /platforms, fileglob: reference-data/platforms/*.json }
        - { load_endpoint: /service-points, fileglob: reference-data/service-points/*.json, dup_override: 422 }
        - { load_endpoint: /instance-storage/instances, fileglob: sample-data/instances/*.json }
        - { load_endpoint: /instance-storage/instances, fileglob: sample-data/instances/*.json }
        - { load_endpoint: /holdings-storage/holdings, fileglob: sample-data/holdingsrecords/*.json }
        - { load_endpoint: /item-storage/items, fileglob: sample-data/items/*.json }
    - mod-inventory-mods
    - mod-circulation-data
    - role: module-sample-data
      module_name: mod-vendors
      repository: "https://github.com/folio-org/mod-vendors"
      files:
        - { load_endpoint: /vendor, fileglob: sample-data/vendors/*.json }
    - mod-auth-demo-users

# Set up stripes
- name: Build stripes webpack, assign permissions
  hosts: stripes-build
  roles:
    - stripes-build
    - tenant-admin-permissions

- name: Build Stripes webpack and container, assign permissions
  hosts: stripes
  roles:
    - stripes-docker
    - tenant-admin-permissions

- name: Build Stripes container
  hosts: snapshot
  roles:
    - stripes-docker

# Roles for packaging
- hosts: vagrant
  roles:
    - maven-3

- hosts: packer
  roles:
    - vagrant-tidy

# Provision a host to support FOLIO Developer Curriculum
- hosts: build_curriculum
  roles:
    - common
    - openjdk-8
    - maven-3
    - nodejs
    - yarn
    - ansible
    - docker-engine

  tasks:
    - name: Move to Node.js 6.X lts
      become: yes
      shell: n lts && touch /etc/.set_nodedefault_ansible
      args:
        creates: /etc/.set_nodedefault_ansible

    - name: Setup Ansible inventory for localhost
      become: yes
      lineinfile:
        dest: /etc/ansible/hosts
        line: localhost ansible_connection=local

    - name: Clone curriculum repository
      git: repo=https://github.com/folio-org/curriculum dest={{ ansible_env.HOME }}/curriculum

