---
# Role to build the raml-module-builder framework
- name: Install prereqs
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - git

- name: Clone raml-module-builder repository
  git: repo=https://github.com/folio-org/raml-module-builder.git dest={{ raml_module_builder_home }}

- name: Build raml-module-builder
  shell: /usr/bin/mvn -q clean install > install.log
  args:
    chdir: "{{ raml_module_builder_home }}"
    creates: "{{ raml_module_builder_home }}/install.log"
