---

- name: Install prereqs from apt for adding repository
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-apt
      - ssl-cert

- name: Install okapi debian package
  become: yes
  apt:
    name: "okapi{% if okapi_version %}={{ okapi_version }}{% endif %}"
    state: present

- name: Enable external hazelcast config if AWS
  set_fact:
    okapi_cluster_config_file: '"-hazelcast-config-file /etc/folio/okapi/hazelcast.xml"'
  when: hazelcast_aws_conf

- name: Install okapi.env
  become: yes
  template: src=okapi.env.j2 dest=/etc/default/okapi
  notify: okapi restart

- name: Install okapi.conf
  become: yes
  template:
    src: okapi.conf.j2
    dest: /etc/folio/okapi/okapi.conf
    owner: okapi
    group: okapi
    mode: 0644
  notify: okapi restart

- name: Install hazelcast.xml
  become: yes
  template:
    src: hazelcast-aws.xml.j2
    dest: /etc/folio/okapi/hazelcast.xml
    owner: okapi
    group: okapi
    mode: 0640
  when: hazelcast_aws_conf
  notify: okapi restart

- name: Install log4j2.properties
  become: yes
  template:
    src: log4j2.properties
    dest: /etc/folio/okapi/log4j2.properties
    owner: okapi
    group: okapi
    mode: 0640
  notify: okapi restart

- name: Initialize okapi database
  become: yes
  shell: /usr/share/folio/okapi/bin/okapi.sh --initdb && touch /var/lib/okapi/.db_init
  args:
    creates: /var/lib/okapi/.db_init
  when: okapi_storage == "postgres"
  notify: okapi restart

- meta: flush_handlers

- name: Make sure Okapi is started
  become: yes
  service: name=okapi state=started
