---
# Provision PostgreSQL database for module data

- name: Install prerequisites from apt
  become: yes
  apt:
    name: [libpq-dev, python-psycopg2, postgresql-client]
    state: present
  when: folio_install_type == "single_server"

# For now, this must be a SUPERUSER (cf. RMB-360)
- name: Create a postgres admin user that can create roles and databases
  postgresql_user:
    login_host: "{{ pg_host }}"
    port: "{{ pg_port }}"
    db: "{{ pg_maint_db }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"
    name: "{{ db_admin_user }}"
    password: "{{ db_admin_password }}"
    encrypted: yes
    # role_attr_flags: CREATEDB,CREATEROLE,LOGIN
    role_attr_flags: SUPERUSER

- name: Create module database
  postgresql_db:
    login_host: "{{ pg_host }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"
    name: "{{ database_name }}"
    owner: "{{ db_admin_user }}"
