---
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
mod_circulation_prefixes:
  - circulation-storage
  - circulation
auth_required: false
admin_user: { username: diku_admin, password: admin }
loan_action: false
admin_permissions:
  - circulation-storage.all
  - circulation.all
