---
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
auth_required: false
top_down_install: false

admin_user: 
  username: diku_admin 
  password: admin 

inv_storage_3: true
do_mods_larger: false
shelf_locations: false
