---
dependencies:
  - role: create-database
    vars:
      pg_host: "{{ pg_host }}"
      db_admin_user: "{{ okapidb_user }}"
      db_admin_password: "{{ okapidb_password }}"
      database_name: "{{ okapidb_name }}"
    when: create_db
