---
# Role to build and deploy FOLIO ui-okapi-console

- name: Clone the ui-okapi-console repository
  become: yes
  git: repo=https://github.com/folio-org/ui-okapi-console.git dest={{ stripes_home }}/ui-okapi-console
  register: console_clone

- name: Install/update packages for ui-okapi-console
  become: yes
  npm: path={{ stripes_home }}/ui-okapi-console
  when: console_clone.changed
  notify: Restart stripes

- name: Link ui-okapi-console into stripes-core
  become: yes
  file:
    src: "{{ stripes_home }}/ui-okapi-console"
    path: "{{ stripes_home }}/stripes-core/node_modules/@folio-sample-modules/ui-okapi-console"
    state: link
  notify: Restart stripes
  
- name: Set up Okapi for stripes
  become: yes
  lineinfile:
    dest: "{{ stripes_home }}/stripes-core/stripes.config.js"
    line: "  okapi: { 'url':'http://localhost:9130', 'tenant':'diku' },"
    insertafter: "^module\\.exports ="
  notify: Restart stripes

- name: Configure stripes to load multiple modules
  become: yes
  lineinfile:
    dest: "{{ stripes_home }}/stripes-core/stripes.config.js"
    line: "    '@folio-sample-modules/trivial': {},"
    regexp: "trivial"
  notify: Restart stripes

- name: Add ui-okapi-console to stripes
  become: yes
  lineinfile:
    dest: "{{ stripes_home }}/stripes-core/stripes.config.js"
    line: "    '@folio-sample-modules/ui-okapi-console': {},"
    insertafter: "trivial"
    backup: yes
  notify: Restart stripes
