---
# Install nodejs and mocha
- name: Install nodejs and npm from apt
  become: yes
  apt:
    name:
      - nodejs
      - npm

- name: Install n and mocha from npm
  become: yes
  npm: name={{ item }} global=yes state=present
  with_items:
    - "n"
    - mocha
