---
# Install nodejs and mocha
- name: Install nodejs and npm from apt
  become: yes
  apt:
    name:
      - nodejs
      - npm
  when: folio_install_type == "single_server"

- name: Install nodejs and npm from apk
  become: yes
  apk:
    name:
      - nodejs
      - npm
    update_cache: yes
  when: folio_install_type == "kubernetes"

- name: Install n from npm
  become: yes
  npm: name="n" global=yes state=present
  when: folio_install_type == "single_server"
