---
- name: Get users for loans
  uri:
    url: "{{ okapi_url }}/users?query=active%3D%22true%22%20and%20type%3D%3Dpatron%20sortby%20personal.lastName%20personal.firstName&limit=6"
    headers:
      Accept: application/json
      X-Okapi-Tenant: "{{ tenant }}"
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token|default('token') }}"
  register: loan_users


# 422 (or 500?) error means the data are already there
- name: Load loans
  uri:
    url: "{{ okapi_url }}/circulation/loans"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('template', item) | to_json }}"
    status_code: 201,422,500
  register: load_loan
  changed_when: load_loan.status == 201
  with_items:
    - loans/bridget-jones-baby-item.json
    - loans/girl-on-the-train-item.json
    - loans/girl-on-the-train-item-3.json
    - loans/girl-on-the-train-item-2.json
    - loans/interesting-times-item.json
    - loans/interesting-times-item-3.json
    - loans/interesting-times-item-2.json
    - loans/nod-item-2.json
    - loans/nod-item.json
    - loans/temeraire-item.json
    - loans/temeraire2-item.json

# 422 error means the data are already there
- name: Load requests
  uri:
    url: "{{ okapi_url }}/request-storage/requests"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('template', item) | to_json }}"
    status_code: 201,422,500
  register: load_request
  changed_when: load_request.status == 201
  with_items:
    - requests/bridget-jones-baby.json
    - requests/girl-on-the-train.json
    - requests/interesting-times.json
    - requests/nod.json
  when: load_requests == true
