---

- name: create build dir
  become: yes
  file: 
    path: "{{ stripes_conf_dir }}"
    state: directory

- name: copy stripes platform files from github project
  become: yes
  git: 
    repo: "{{ stripes_github_project }}"
    dest: "{{ stripes_conf_dir }}"
    version: "{{ stripes_github_version }}"
    update: no

- name: copy genStripesModDescriptors.sh to build dir
  become: yes
  copy: 
    src: genStripesModDescriptors.sh 
    dest: {{ stripes_conf_dir}}/genStripesModDescriptors.sh
    mode: 0755

- name: copy yarn.lock file to stripes_conf_dir
  become: yes
  get_url: 
    url: "{{ folio_snapshot_url }}/yarn.lock"
    dest: "{{ stripes_conf_dir }}"
  when: use_folio_snapshot
  notify: "Rebuild stripes" 

- name: Move to Node.js 6.X lts
  become: yes
  shell: n lts && touch {{ stripes_conf_dir }}/.set_nodedefault_ansible
  args:
    creates: "{{ stripes_conf_dir }}/.set_nodedefault_ansible"

- name: copy npmrc configuration 
  become: yes
  template: 
    src: "{{ item.src }}"
    dest: "{{ stripes_conf_dir }}/{{ item.dest }}"
  with_items:
    - { src: 'npmrc.j2', dest: '.npmrc' }
  notify: "Rebuild stripes"

- name: copy yarnrc configuration
  become: yes
  template:
    src: yarnrc.j2
    dest: "{{ stripes_conf_dir }}/.yarnrc"
  when: npm_proxy == true
  notify: "Rebuild stripes"

- name: Ensure modules are registered
  command: /bin/true
  when: okapi_register_modules == true
  notify: "Register modules"

- name: Ensure modules are enabled for tenants
  command: /bin/true
  when: okapi_enable_modules
  notify: "Enable modules"

- meta: flush_handlers 
