---
- wait_for: timeout=5

- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: tenant_admin_login
  changed_when: tenant_admin_login.status == 201

- name: Configure RM API credentials
  uri:
    url: "{{ okapi_url }}/eholdings/kb-credentials"
    method: POST
    body_format: json
    headers:
      Authtoken-Refresh-Cache: "true"
      X-Okapi-Tenant: "{{ tenant }}"
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
      Accept: application/json
    body: '{ "data": { "type": "kbCredentials", "attributes": { "name": "{{ tenant }}", "apiKey": "{{ rmapi_key }}", "url": "{{ rmapi_url }}", "customerId": "{{ rmapi_custid }}" } } }'
    status_code: 201,422
  register: mod_codex_ekb_credentials
  changed_when: mod_codex_ekb_credentials.status == 201
