---
# Role to load module sample data
- name: Create sample data directory on control host
  file: path={{ working_dir }} state=directory
  vars:
    ansible_become: false
  delegate_to: 127.0.0.1

- name: Clone repo with sample data
  git: repo={{ repository }} dest={{ working_dir }}/{{ module_name }} version={{ module_version }} update={{ update_repo }} force={{ force_repo_update }}
  vars:
    ansible_become: false
  delegate_to: 127.0.0.1

- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: tenant_admin_login
  when: auth_required

- name: Load module data
  include: load-data.yml load_endpoint={{ item.load_endpoint }} fileglob={{ item.fileglob }} dup_key={{ item.dup_override|default(duplicate_key_error) }}
  with_items: "{{ files }}"
