---
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
folio_user: folio
tenant: diku
docker_repo: folioci  
pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
module_database: okapi_modules
# default dockerCMD values for modules
docker_cmd:
  mod-login:
    - "verify.user=true"
# default env values for modules
env_var:
  mod-inventory:
    - { name: JAVA_OPTS, value: "-Dorg.folio.metadata.inventory.storage.type=okapi" }
