---
# Role to build a Docker image from source and launch with Okapi
- name: Check status of mod-users deployment
  uri:
    url: http://localhost:9130/_/discovery/modules/mod-users
    status_code: 200, 404
  when: mod_users_clone.changed
  register: mod_users_deploy_status

- name: Set fact - instId for mod-users
  set_fact: mod_users_instid={{ mod_users_deploy_status.json.0.instId }}
  when:
    - mod_users_clone.changed
    - mod_users_deploy_status.status == 200

- name: Undeploy mod-users module if repo updated
  uri:
    url: http://localhost:9130/_/discovery/modules/mod-users/{{ mod_users_instid }}
    method: DELETE
    status_code: 204, 404
  when:
    - mod_users_clone.changed
    - mod_users_deploy_status.status == 200
  register: mod_users_undeploy
  changed_when: "mod_users_undeploy.status == 204"

- name: Un-register mod-users if repository updated
  uri:
    url: http://localhost:9130/_/proxy/modules/mod-users
    method: DELETE
    status_code: 204, 404
  when: mod_users_clone.changed
  register: mod_users_unreg
  changed_when: "mod_users_unreg.status == 204"

- name: Remove mod-users image if repository updated
  become: yes
  docker_image: name=mod-users state=absent force=yes
  when: mod_users_clone.changed

- name: Build mod-users Docker image
  become: yes
  docker_image: name=mod-users path={{ mod_users_src_home }}

- name: Check mod-users module registration
  uri:
    url: http://localhost:9130/_/proxy/modules/mod-users
    status_code: 200, 404
  register: mod_users_reg_status

- name: Register mod-users module
  uri:
    url: http://localhost:9130/_/proxy/modules
    method: POST
    body_format: json
    body: "{{ lookup('file', 'ModuleDescriptor.json') }}"
    status_code: 201
  when: mod_users_reg_status.status == 404
  register: mod_users_reg
  changed_when: "mod_users_reg.status == 201"

- name: Check mod-users module deployment
  uri:
    url: http://localhost:9130/_/discovery/modules/mod-users
    status_code: 200, 404
  register: mod_users_deploy_status

- name: Deploy mod-users module
  uri:
    url: http://localhost:9130/_/discovery/modules
    method: POST
    HEADER_Content-Type: application/json
    body: '{ "srvcId" : "mod-users", "nodeId" : "localhost" }'
    status_code: 201
  when: mod_users_deploy_status.status == 404
  register: mod_users_deploy
  changed_when: "mod_users_deploy.status == 201"

- name: Give mod_users a chance to spin up
  pause: seconds=10
  when: mod_users_deploy.changed == true

