---
# Role to serve a stripes webpack via nginx

- name: Install nginx from apt
  become: yes
  apt: name=nginx

- name: Ensure nginx is running
  become: yes
  service: name=nginx state=started
  ignore_errors: yes

- name: Get status of install.json
  stat: path=/etc/folio/okapi/install.json
  register: stat_install_json

- name: Install stripes configuration for nginx
  become: yes
  template: src=stripes.conf.j2 dest=/etc/nginx/sites-available/stripes
  notify: Restart nginx

- name: Link stripes configuration into sites-enabled
  become: yes
  file: src=/etc/nginx/sites-available/stripes path=/etc/nginx/sites-enabled/stripes state=link
  notify: Restart nginx

- meta: flush_handlers
