---
# Role to build a Docker image from source and launch with Okapi
- name: Check diku tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants/diku
    status_code: 200, 404
  register: diku_status

- name: Create diku tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants
    method: POST
    body_format: json
    body: "{{ lookup('file','diku.json') }}"
    status_code: 201
  when: diku_status.status == 404
  register: diku_tenant
  changed_when: "diku_tenant.status == 201"

- name: Remove mod-circulation for tenant if repository updated
  uri:
    url: http://localhost:9130/_/proxy/tenants/diku/modules/mod-circulation
    method: DELETE
    status_code: 204, 404
  when: mod_circulation_clone.changed
  register: mod_circ_diku_delete
  changed_when: "mod_circ_diku_delete.status == 204"

- name: Undeploy mod-circulation module if repo updated
  uri:
    url: http://localhost:9130/_/discovery/modules/mod-circulation
    method: DELETE
    status_code: 204, 404
  when: mod_circulation_clone.changed
  register: mod_circ_undeploy
  changed_when: "mod_circ_undeploy.status == 204"

- name: Un-register mod-circulation if repository updated
  uri:
    url: http://localhost:9130/_/proxy/modules/mod-circulation
    method: DELETE
    status_code: 204, 404
  when: mod_circulation_clone.changed
  register: mod_circ_unreg
  changed_when: "mod_circ_unreg.status == 204"

- name: Remove mod-circulation image if repository updated
  docker_image: name=mod-circulation state=absent
  when: mod_circulation_clone.changed

- name: Build mod-circulation Docker image
  docker_image: name=mod-circulation path={{ mod_circulation_src_home }}

- name: Check mod-circulation module registration
  uri:
    url: http://localhost:9130/_/proxy/modules/mod-circulation
    status_code: 200, 404
  register: mod_circ_reg_status

- name: Register mod-circulation module
  uri:
    url: http://localhost:9130/_/proxy/modules
    method: POST
    body_format: json
    body: "{{ lookup('file', 'ModuleDescriptor.json') }}"
    status_code: 201
  when: mod_circ_reg_status.status == 404
  register: mod_circ_reg
  changed_when: "mod_circ_reg.status == 201"

- name: Check mod-circulation module deployment
  uri:
    url: http://localhost:9130/_/discovery/modules/mod-circulation
    status_code: 200, 404
  register: mod_circ_deploy_status

- name: Deploy mod-circulation module
  uri:
    url: http://localhost:9130/_/discovery/modules
    method: POST
    HEADER_Content-Type: application/json
    body: '{ "srvcId" : "mod-circulation", "nodeId" : "localhost" }'
    status_code: 201
  when: mod_circ_deploy_status.status == 404
  register: mod_circ_deploy
  changed_when: "mod_circ_deploy.status == 201"

# will always register as changed
- name: Enable mod-circulation module for tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants/diku/modules
    method: POST
    body_format: json
    body: '{ "id" : "mod-circulation" }'
  register: mod_circ_enable
  changed_when: mod_circ_enable.status == 200
