---
folio_user: okapi
mod_users_home: /usr/share/folio/mod-users
mod_users_conf: /etc/folio/mod-users
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
okapi_host: "{{ ansible_default_ipv4.address }}"
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
pg_user: "{{ pg_admin_user }}"
pg_password: "{{ pg_admin_password }}"
mod_users_db: mod_users
