---
- name: get available interfaces on supertenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/supertenant/interfaces"
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    status_code: 200
  retries: 5
  delay: 3
  register: supertenant_interfaces_response
  until: supertenant_interfaces_response.status == 200

- name: set list of interfaces on supertenant
  set_fact:
    supertenant_interfaces: "{{ supertenant_interfaces_response | json_query('json[].id') }}"

- name: get login token if supertenant is secured (authtoken is present)
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    body_format: json
    body: "{'username': '{{ superuser_username }}', 'password': '{{ superuser_password }}' }"
    status_code: 201
  register: login_result
  when: '"authtoken" in supertenant_interfaces'

- name: Set Okapi token if supertenant is secured
  set_fact:
    supertenant_token: "{{ login_result['x_okapi_token'] }}" 
  when: '"authtoken" in supertenant_interfaces'
