---
folio_user: folio
mod_auth_home: /usr/share/folio/mod-auth
mod_auth_conf: /etc/folio/mod-auth
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
pg_user: "{{ pg_admin_user }}"
pg_password: "{{ pg_admin_password }}"
mod_auth_db: mod_auth
mod_auth_modules:
  - { index: 0, module: authtoken-module, docker_image: folioci/mod-authtoken }
  - { index: 1, module: login-module, docker_image: folioci/mod-login }
  - { index: 2, module: permissions-module, docker_image: folioci/mod-permissions }

