---
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
install_url: http://folio-snapshot-stable.aws.indexdata.com/install.json
tenant: diku
install_timeout: 600
install_deploy: no
pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
module_database: okapi_modules
module_env:
  - name: db.host
    value: "{{ pg_host }}"
  - name: db.port
    value: "{{ pg_port }}"
  - name: db.database
    value: "{{ module_database }}"
  - name: db.username
    value: "{{ pg_admin_user }}"
  - name: db.password
    value: "{{ pg_admin_password }}"
