---
- name: Create Okapi postgresql user
  postgresql_user:
    db: postgres
    login_host: "{{ pg_host }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"
    name: "{{ okapi_db_user }}"
    password: "{{ okapi_db_password }}"
    role_attr_flags: CREATEDB
    no_password_changes: yes
  when: create_db

- name: Create Okapi db
  postgresql_db:
    login_host: "{{ pg_host }}"
    login_user: "{{ okapi_db_user }}"
    login_password: "{{ okapi_db_password }}"
    name: "{{ okapi_db_database }}"
    owner: "{{ okapi_db_user }}"
  when: create_db

- name: create hazelcast service account
  k8s:
    state: present
    definition: "{{ lookup('template', 'rbac.yml.j2') }}"

- name: create okapi service
  k8s:
    state: present
    definition: "{{ lookup('template', 'okapi-service.yml.j2') }}"

- name: create hazelcast configmap
  k8s:
    state: present
    definition: "{{ lookup('template', 'hazelcast-configmap.yml.j2') }}"

- name: create okapi deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'okapi-deployment.yml.j2') }}"

- name: create okapi ingress
  k8s:
    state: present
    definition: "{{ lookup('template', 'okapi-ingress.yml.j2') }}"
  when: create_ingress
