---
- name: create db creation configmap
  k8s:
    state: present
    definition: "{{ lookup('template', 'db-create-configmap.yml.j2') }}"

- name: create db creation job
  k8s:
    state: present
    definition: "{{ lookup('template', 'db-create-job.yml.j2') }}"

- name: create hazelcast service account
  k8s:
    state: present
    definition: "{{ lookup('template', 'rbac.yml.j2') }}"

- name: create okapi service
  k8s:
    state: present
    definition: "{{ lookup('template', 'okapi-service.yml.j2') }}"

- name: create hazelcast configmap
  k8s:
    state: present
    definition: "{{ lookup('template', 'hazelcast-configmap.yml.j2') }}"

- name: create okapi deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'okapi-deployment.yml.j2') }}"

- name: create okapi ingress
  k8s:
    state: present
    definition: "{{ lookup('template', 'okapi-ingress.yml.j2') }}"
  when: create_ingress

- name: clean up db creation configmap
  k8s:
    state: absent
    definition: "{{ lookup('template', 'db-create-configmap.yml.j2') }}"
