---
# Role to enable mod-users for the sample tenant and load sample data
- name: Check tenant mod-user registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules/users-module"
    status_code: 200, 404
  register: tenant_mod_users

- name: Enable mod-users module for tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules"
    method: POST
    body_format: json
    body: '{ "id" : "users-module" }'
    status_code: 201
  register: mod_users_enable
  changed_when: mod_users_enable.status == 201
  when: tenant_mod_users.status == 404

# This should really only happen if the users aren't already there
# 400 error means the user is already there, this is not ideal
- name: Load users
  uri:
    url: "{{ okapi_url }}/users"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
    body: "{{ lookup('file', item) }}"
    status_code: 201,400
  register: load_user
  ignore_errors: yes
  changed_when: load_user.status == 201
  with_fileglob:
    - User*.json

