---
# Role to enable mod-users for the sample tenant and load sample data
- name: Enable mod-users module for tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants/diku/modules
    method: POST
    body_format: json
    body: '{ "id" : "mod-users" }'
  register: mod_users_enable
  changed_when: mod_users_enable.status == 200

- name: Load a user
  uri:
    url: http://localhost:9130/users
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
    body: "{{ lookup('file', item) }}"
    status_code: 201
  register: load_user
  changed_when: load_user.status == 201
  with_fileglob:
    - User*.json
    
