---
# # Create Secret for required connection
- name: create Secret DB Connection
  k8s:
    state: "{{ k8s_state }}"
    definition: "{{ lookup('template', 'db-secrets.yml.j2') }}"
  when: create_secret

# Pull folio-org/folio-ansible repository from latest group_vars/snapshot
- name: Pull Latest Module Options
  uri:
    url: "{{folio_options_url}}"
    return_content: yes
  register: result

- name: Set Module Options
  set_fact:
    module_options: "{{ result.content | from_yaml }}"

- name: debug folio_modules
  debug:
    var: module_item
  loop: "{{ folio_modules }}"
  loop_control:
    loop_var: module_item
  when: module_item.deploy is defined and module_item.deploy

- name: get deployed mods
  uri:
    url: "{{ okapi_url }}/_/discovery/modules"
  register: deployed_modules_req

- name: set deployed modules list
  set_fact:
    deployed_modules: "{{ deployed_modules_req.json | json_query('[].srvcId') }}"

# loop over module_list variables to deploy backend module deployment and service
- include_tasks: module.yml
  loop: "{{ folio_modules }}"
  loop_control:
    loop_var: module_item
  when: module_item.deploy is defined and module_item.deploy
