---
# # Create Secret for required connection
- name: create Secret DB Connection
  k8s:
    state: "{{ k8s_state }}"
    definition: "{{ lookup('template', 'db-secrets.yml.j2') }}"

# Pull folio-org/folio-ansible repository from latest group_vars/snapshot
- name: Pull Latest Module Options
  uri:
    url: "{{folio_options_url}}"
    return_content: yes
  register: result

- name: Set Module Descriptor 
  set_fact:
    module_options: "{{ result.content | from_yaml }}"

# loop over module_list variables to deploy backend module deployment and service 
- include_tasks: module.yml
  loop: "{{ module_list }}"
  loop_control:
    loop_var: module_item
